let themeData = [
  {
    "name": "bluePink",
    "bg": "#1e293b",
    "bg-focus": "#334155",
    "primary-clear": "#2563eb",
    "primary-dull": "#bfdbfe",
    "primary-visible": "#D3E6FE",
    "accent-clear": "#d946ef",
    "accent-dull": "#fae8ff",
    "clear": "#cbd5e1",
    "dull": "#94a3b8",
    "duller": "#475569",
  },
  {
    "name": "greenAmber",
    "bg": "#fafaf9",
    "bg-focus": "#f5f5f4",
    "primary-clear": "#86efac",
    "primary-dull": "#f0fdf5",
    "primary-visible": "#19725D",
    "accent-clear": "#f5be0b",
    "accent-dull": "#fef1c7",
    "clear": "#292524",
    "dull": "#78716c",
    "duller": "#E0E2E5",
  },
  {
    "name": "pinkBeige",
    "bg": "#FFFBF5",
    "bg-focus": "#F7EFE5",
    "primary-clear": "#9a3197",
    "primary-dull": "#f5d7f7",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#f59e0b",
    "accent-dull": "#fef3c7",
    "clear": "#292524",
    "dull": "#78716c",
    "duller": "#EAD5BA"
  },
  {
    "bg": "#222831",
    "bg-focus": "#393E46",
    "primary-clear": "#00ADB5",
    "primary-dull": "#AAE3E2",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#D9ACF5",
    "accent-dull": "#fff4ff",
    "clear": "#EEEEEE",
    "dull": "#FDEBED",
    "duller": "#454e59",
  },
  {
    "bg": "#567189",
    "bg-focus": "#7B8FA1",
    "primary-clear": "#f7bf7a",
    "primary-dull": "#CFB997",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#6f8aa1",
    "accent-dull": "#9eb2c2",
    "clear": "#EEEEEE",
    "dull": "#FDEBED",
    "duller": "#c6d2db",
  },
  {
    "bg": "#DDDDDD",
    "bg-focus": "#EEEEEE",
    "primary-clear": "#658864",
    "primary-dull": "#B7B78A",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#bc6c25",
    "accent-dull": "#ecd79b",
    "clear": "#292524",
    "dull": "#78716c",
    "duller": "#d1d1d1"
  },
  {
    "bg": "#13005A",
    "bg-focus": "#00337C",
    "primary-clear": "#03C988",
    "primary-dull": "#ebfef5",
    "primary-visible": "#cefde5",
    "accent-clear": "#a1f9d0",
    "accent-dull": "#00815b",
    "clear": "#EEEEEE",
    "dull": "#FDEBED",
    "duller": "#004cd7",
  },
  {
    "bg": "#F4EEFF",
    "bg-focus": "#DCD6F7",
    "primary-clear": "#424874",
    "primary-dull": "#A6B1E1",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#D9ACF5",
    "accent-dull": "#FFCEFE",
    "clear": "#292524",
    "dull": "#64748b",
    "duller": "#bbb9e9"
  },
  {
    "bg": "#2B2E4A",
    "bg-focus": "#53354A",
    "primary-clear": "#E84545",
    "primary-dull": "#903749",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#03C988",
    "accent-dull": "#a1f9d0",
    "clear": "#EEEEEE",
    "dull": "#FDEBED",
    "duller": "#31355b",
  },
  {
    "bg": "#355C7D",
    "bg-focus": "#6C5B7B",
    "primary-clear": "#F67280",
    "primary-dull": "#C06C84",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#03C988",
    "accent-dull": "#FFCEFE",
    "clear": "#EEEEEE",
    "dull": "#FDEBED",
    "duller": "#4e84a9",
  },
  {
    "bg": "#576F72",
    "bg-focus": "#7D9D9C",
    "primary-clear": "#E4DCCF",
    "primary-dull": "#F0EBE3",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#03C988",
    "accent-dull": "#FFCEFE",
    "clear": "#EEEEEE",
    "dull": "#FDEBED",
    "duller": "#292524",
  },
  {
    "bg": "#222831",
    "bg-focus": "#393E46",
    "primary-clear": "#FFD369",
    "primary-dull": "#EEEEEE",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#cfdbd5",
    "accent-dull": "#e8eddf",
    "clear": "#EEEEEE",
    "dull": "#FDEBED",
    "duller": "#292524",
  },

  {
    "bg": "#293241",
    "bg-focus": "#3d5a80",
    "primary-clear": "#ee6c4d",
    "primary-dull": "#EEEEEE",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#98c1d9",
    "accent-dull": "#e0fbfc",
    "clear": "#EEEEEE",
    "dull": "#b4b4b4",
    "duller": "#495f80",
  },
  {
    "bg": "#401D19",
    "bg-focus": "#62403c",
    "primary-clear": "#ee6c4d",
    "primary-dull": "#EEEEEE",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#98c1d9",
    "accent-dull": "#e0fbfc",
    "clear": "#FF682C",
    "dull": "#ffe7e0",
    "duller": "#8c514a",
  },
  {
    "bg": "#fffffc",
    "bg-focus": "#ffc6ff",
    "primary-clear": "#bdb2ff",
    "primary-dull": "#bdb2ff",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#ffadad",
    "accent-dull": "#ffd6a5",
    "clear": "#22223b",
    "dull": "#4b498a",
    "duller": "#b4e1ff",
  },
  {
    "bg": "#edf2f4",
    "bg-focus": "#d9dee4",
    "primary-clear": "#d90429",
    "primary-dull": "#ff98aa",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#ffadad",
    "accent-dull": "#ffd6a5",
    "clear": "#4b4f5d",
    "dull": "#6a738b",
    "duller": "#bfc7d1",
  },
  {
    "bg": "#F0F5F9",
    "bg-focus": "#C9D6DF",
    "primary-clear": "#1E2022",
    "primary-dull": "#34373b",
    "primary-visible": "#F0F5F9",
    "accent-clear": "#788189",
    "accent-dull": "#e1e4e6",
    "clear": "#1E2022",
    "dull": "#52616B",
    "duller": "#bfc7d1",
  },
  {
    "bg": "#F0ECE3",
    "bg-focus": "#DFD3C3",
    "primary-clear": "#596E79",
    "primary-dull": "#788e98",
    "primary-visible": "#F0F5F9",
    "accent-clear": "#788189",
    "accent-dull": "#e1e4e6",
    "clear": "#1E2022",
    "dull": "#52616B",
    "duller": "#C7B198",
  },
  {
    "bg": "#FFFFFF",
    "bg-focus": "#E3F6F5",
    "primary-clear": "#272343",
    "primary-dull": "#788e98",
    "primary-visible": "#F0F5F9",
    "accent-clear": "#788189",
    "accent-dull": "#e1e4e6",
    "clear": "#1E2022",
    "dull": "#52616B",
    "duller": "#BAE8E8",
  },
  {
    "bg": "#393232",
    "bg-focus": "#8D6262",
    "primary-clear": "#ED8D8D",
    "primary-dull": "#CFB997",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#6f8aa1",
    "accent-dull": "#9eb2c2",
    "clear": "#EEEEEE",
    "dull": "#FDEBED",
    "duller": "#4D4545",
  },
  {
    "bg": "#EEEBDD",
    "bg-focus": "#DFD3C3",
    "primary-clear": "#810000",
    "primary-dull": "#630000",
    "primary-visible": "#F0F5F9",
    "accent-clear": "#788189",
    "accent-dull": "#e1e4e6",
    "clear": "#1E2022",
    "dull": "#52616B",
    "duller": "#C7B198",
  },
  {
    "bg": "#EEEBDD",
    "bg-focus": "#DFD3C3",
    "primary-clear": "#064420",
    "primary-dull": "#E4EFE7",
    "primary-visible": "#E4EFE7",
    "accent-clear": "#788189",
    "accent-dull": "#e1e4e6",
    "clear": "#1E2022",
    "dull": "#52616B",
    "duller": "#C7B198",
  },
  {
    "bg": "#FFEADB",
    "bg-focus": "#DFD3C3",
    "primary-clear": "#FF9A76",
    "primary-dull": "#E4EFE7",
    "primary-visible": "#E4EFE7",
    "accent-clear": "#679B9B",
    "accent-dull": "#e1e4e6",
    "clear": "#1E2022",
    "dull": "#52616B",
    "duller": "#C7B198",
  },
  {
    "bg": "#FCEEF5",
    "bg-focus": "#ffffff",
    "primary-clear": "#E05297",
    "primary-dull": "#F3BAD6",
    "primary-visible": "#E0E2E5",
    "accent-clear": "#f5be0b",
    "accent-dull": "#fef1c7",
    "clear": "#292524",
    "dull": "#78716c",
    "duller": "#FAD9E6",
  },
  {
    "bg": "#FCEEF5",
    "bg-focus": "#ffffff",
    "primary-clear": "#61C0BF",
    "primary-dull": "#BBDED6",
    "primary-visible": "#E0E2E5",
    "accent-clear": "#FFB6B9",
    "accent-dull": "#FAE3D9",
    "clear": "#292524",
    "dull": "#78716c",
    "duller": "#FAD9E6",
  },
  {
    "bg": "#F8F3D4",
    "bg-focus": "#ffffff",
    "primary-clear": "#00B8A9",
    "primary-dull": "#BBDED6",
    "primary-visible": "#E0E2E5",
    "accent-clear": "#F6416C",
    "accent-dull": "#FAE3D9",
    "clear": "#292524",
    "dull": "#78716c",
    "duller": "#FAD9E6",
  },
  {
    "bg": "#222831",
    "bg-focus": "#393E46",
    "primary-clear": "#892CDC",
    "primary-dull": "#BC6FF1",
    "primary-visible": "#fdf6fd",
    "accent-clear": "#D9ACF5",
    "accent-dull": "#fff4ff",
    "clear": "#EEEEEE",
    "dull": "#FDEBED",
    "duller": "#454e59",
  },

]

export default themeData;
